=== milosnrt219/nrt_2_19/oglasi.dtd
<!ELEMENT oglasi (oglas+)>
<!ELEMENT oglas (KategorijaOglasa,DatumIsteka,Cena,TekstOglasa,Oznaka*,Email*)>
<!ELEMENT KategorijaOglasa (#PCDATA)>
<!ELEMENT DatumIsteka (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT TekstOglasa (#PCDATA)>
<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

<!ATTLIST KategorijaOglasa tip (alati|automobili|stanovi|poducavanje) #REQUIRED>
<!ATTLIST Cena valuta (din|eur|usd) "din">
<!ATTLIST Email tip (sluzbeni|privatni) #REQUIRED>

=== milosnrt219/nrt_2_19/oglasi.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE oglasi SYSTEM "oglasi.dtd">
<oglasi>
    <oglas>
        <KategorijaOglasa tip="alati"></KategorijaOglasa>
        <DatumIsteka>
            <Dan>15</Dan>
            <Mesec>09</Mesec>
            <Godina>2023</Godina>
        </DatumIsteka>
        <Cena valuta="din">20000</Cena>
        <TekstOglasa>Motorna Testera NOVO</TekstOglasa>
        <Oznaka>Motorna Testera</Oznaka>
        <Oznaka>Demon Pro</Oznaka>
        <Oznaka>4.4 KS</Oznaka>
        <Email>
            <Kontakt tip="sluzbeni">milosnrt@gmail.com</Kontakt>
            <Kontakt tip="privatni">milos@gmail.com</Kontakt>
        </Email>
        
    </oglas>
</oglasi>
